name: Test ubuntu-latest

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: "Test ubuntu-latest"
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: "Ubuntu release"
        run: lsb_release -a

      - name: "Ubuntu version"
        run: cat /etc/os-release

      - name: "Update apt"
        run: apt update
